---
title: "Growth Modeling for KNOT Data"
output: html_notebook
---

```{r}
getwd()
```

```{r}
library(ggplot2)
library(psych)
library(reshape)
library(nlme)
```

```{r}
all_data <- read.csv("/Volumes/My Passport/Curiosity/v6/Data/KNOT/KNOT_data_v2.csv", header = TRUE)
```

```{r}
head(all_data)
```


```{r}
# create longitudinal plot for compressibility
plot_obs <- ggplot(data = all_data, aes(x = Node, y = C, group = ID))
print(plot_obs + geom_line())
```

```{r}
# create longitudinal plot for DoF
# plot_obs <- ggplot(data = all_data, aes(x = Node, y = DoF, group = ID))
# print(plot_obs + geom_line())
```

```{r}
# create longitudinal plot for Betti
plot_obs <- ggplot(data = all_data, aes(x = Node, y = Betti, group = ID))
print(plot_obs + geom_line())
```


```{r}
# No growth model
betti_NG <- lme(fixed = Betti ~ 1, 
              data = all_data,
              random = ~ 1 | ID, 
              na.action = na.omit)
summary(betti_NG)
```


```{r}
all_data$pred_betti_NG <- predict(betti_NG)
all_data$resid_betti_NG <- residuals(betti_NG)
```

```{r}
# plotting PREDICTED intra-individual change
ggplot(data = all_data, aes(x = Node, y = pred_betti_NG, group = ID)) +
  ggtitle("No Growth Model: Betti Curves") +
  geom_point() + 
  geom_line() +
  xlab("Node") + 
  ylab("PREDICTED Betti Curve") +
  geom_hline(yintercept = 17.59, linetype = "dashed", color = "red")
```
```{r}
# Linear growth
betti_LG <- lme(fixed = Betti ~ 1 + Node, 
              data = all_data,
              random = ~ 1 | ID, 
              na.action = na.omit)
summary(betti_LG)
```

```{r}
# Place individual predictions and residuals into the dataframe
all_data$pred_betti_LG <- predict(betti_LG)
all_data$resid_betti_LG <- residuals(betti_LG)
```

```{r}
# Create a function for the prototype
fun_LG <- function(x) {
  -11.85 + 0.407*x
}
```

```{r}
# plotting PREDICTED intra-individual change
ggplot(data = all_data, aes(x = Node, y = pred_betti_LG, group = ID)) +
  ggtitle("Linear Growth & Random Intercept") +
  geom_point() + 
  geom_line() +
  xlab("Node") + 
  ylab("PREDICTED Betti Curve") +
  stat_function(fun = fun_LG, color = "red", size = 1, linetype = "dashed")
```

```{r}
# Random slope
betti_LGRS <- lme(fixed = Betti ~ 1 + Node, 
              data = all_data,
              random = ~ 1 + Node | ID, 
              na.action = na.omit)
summary(betti_LGRS)
```

```{r}
# Place individual predictions and residuals into the dataframe
all_data$pred_betti_LGRS <- predict(betti_LGRS)
all_data$resid_betti_LGRS <- residuals(betti_LGRS)
```

```{r}
# Create a function for the prototype
fun_LGRS <- function(x) {
  -7.17 + 0.31*x
}
```

```{r}
# plotting PREDICTED intra-individual change
ggplot(data = all_data, aes(x = Node, y = pred_betti_LGRS, group = ID)) +
  ggtitle("Linear Growth, Random Intercept, Random Slope") +
  geom_point() + 
  geom_line() +
  xlab("Node") + 
  ylab("PREDICTED Betti Curve") +
  stat_function(fun = fun_LGRS, color = "red", size = 1, linetype = "dashed")
```

```{r}
# Quadratic growth
all_data$NodeQuad <- all_data$Node * all_data$Node
betti_QG <- lme(fixed = Betti ~ 1 + Node + NodeQuad, 
              data = all_data,
              random = ~ 1 | ID, 
              na.action = na.omit)
summary(betti_QG)
```

```{r}
# Place individual predictions and residuals into the dataframe
all_data$pred_betti_QG <- predict(betti_QG)
all_data$resid_betti_QG <- residuals(betti_QG)
```

```{r}
# Create a function for the prototype
fun_QG <- function(x) {
  -2.28 + 0.15*x + 0.00097*x*x
}
```

```{r}
# plotting PREDICTED intra-individual change
ggplot(data = all_data, aes(x = Node, y = pred_betti_QG, group = ID)) +
  ggtitle("Quadratic Growth") +
  geom_point() + 
  geom_line() +
  xlab("Node") + 
  ylab("PREDICTED Betti Curve") +
  stat_function(fun = fun_QG, color = "red", size = 1, linetype = "dashed")
```

```{r}
# Quadratic growth, random coefficients
betti_QGRS <- lme(fixed = Betti ~ 1 + Node + NodeQuad, 
              data = all_data,
              random = ~ 1 + Node + NodeQuad | ID, 
              na.action = na.omit)
summary(betti_QGRS)
```

```{r}
# Place individual predictions and residuals into the dataframe
all_data$pred_betti_QGRS <- predict(betti_QGRS)
all_data$resid_betti_QGRS <- residuals(betti_QGRS)
```

```{r}
# Create a function for the prototype
fun_QGRS <- function(x) {
  -0.575 + 0.069*x + 0.0018278*x*x
}
```

```{r}
# plotting PREDICTED intra-individual change
ggplot(data = all_data, aes(x = Node, y = pred_betti_QGRS, group = ID)) +
  ggtitle("Quadratic Growth, Random Intercept, Random Slope") +
  geom_point() + 
  geom_line() +
  xlab("Node") + 
  ylab("PREDICTED Betti Curve") +
  stat_function(fun = fun_QGRS, color = "red", size = 1, linetype = "dashed")
```

```{r}
betti_cur <- lme(fixed = Betti ~ 1 + Node + NodeQuad + DS + NodeQuad:DS + SC + NodeQuad:SC + ST + NodeQuad:ST + TS + NodeQuad:TS + JE + NodeQuad:JE + num_edges + NodeQuad:num_edges + num_nodes + NodeQuad:num_nodes, 
              data = all_data,
              random = ~ 1 + Node + NodeQuad | ID, 
              na.action = na.omit)
summary(betti_cur)
```

```{r}
# Place individual predictions and residuals into the dataframe
all_data$pred_betti_full <- predict(betti_cur)
all_data$resid_betti_full <- residuals(betti_cur)
```

```{r}
plot(betti_cur)
```

```{r}
ggplot(all_data, aes(x = all_data$resid_betti_full, y = pred_betti_full)) + geom_point()
```

```{r}
# create longitudinal plot for Betti
plot_obs <- ggplot(data = all_data, aes(x = Node, y = Betti, group = ID))
print(plot_obs + geom_line())
```

```{r}
betti_cur <- lme(fixed = Betti ~ 1 + Node + DS + Node:DS + num_edges + Node:num_edges + num_nodes + Node:num_nodes, 
              data = all_data,
              random = ~ 1 + Node | ID, 
              na.action = na.omit)
summary(betti_cur)
```

```{r}
# Place individual predictions and residuals into the dataframe
all_data$pred_betti_full <- predict(betti_cur)
all_data$resid_betti_full <- residuals(betti_cur)
```

```{r}
# plotting PREDICTED intra-individual change
ggplot(data = all_data, aes(x = Node, y = pred_betti_full, group = ID)) +
  ggtitle("Growth Model") +
  geom_point() + 
  geom_line() +
  xlab("Node") + 
  ylab("PREDICTED Betti Curve") 
```

```{r}
plot(betti_cur)
```



```{r}
ggplot(all_data, aes(x = all_data$resid_betti_full, y = pred_betti_full)) + geom_point()
```

